sudo: required

#services:
#    - docker

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y python-pip zlib1g-dev python-lxml libxml2-dev libxslt1-dev python-dev libboost-dev libboost-python-dev libssh-dev libcurl4-openssl-dev libtool unzip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink pkg-config && brew install python boost-python libssh jq pkg-config; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ydkdev/confd-beta; fi

script:
    - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
    - export REPO=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_REPO_SLUG; else echo `curl -s $PR | jq -r .head.repo.full_name`; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, REPO=$REPO"
    - export YDK_HOME_DIR=`pwd`
#    - virtualenv myenv
#    - source myenv/bin/activate
#    - pip install -r requirements.txt
#    - python generate.py --profile profiles/test/ydktest.json
#    - pip install gen-api/python/dist/*
#    - export PYTHONPATH=gen-api/python:$PYTHONPATH
#    - python gen-api/python/tests/test_sanity_codec.py
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/CiscoDevNet/ydk-gen/files/405684/confd-basic-6.2.linux.x86_64.zip && unzip confd-basic-6.2.linux.x86_64.zip -d tmp && ./tmp/*.bin confd && cd confd && source confdrc && cp $YDK_HOME_DIR/test/confd.conf etc/confd && cd $YDK_HOME_DIR; fi
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then confd -c confd/etc/confd/confd.conf && confd --status ; fi
#    - cd test && sudo ./test_native_ydk.py
#    - cd ..
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/travis_ci.sh ; fi

